### PR TITLE
functions in setTimeout have to use socialNetwork instead of $sn

### PR DESCRIPTION
**Pull request by senky**
`setTimeout` function calls function defined in the first parametre in global scoope. This means, we cannot use `$sn` shortcut.

### CODE REVIEW

**Comment by Kamahl19** [comment]
what errors was this causing?

**Comment by senky** [comment]
Javascript errors, @Culprit-CZ knows more.

**Comment by Kamahl19** [comment]
MA

**Comment by Culprit-CZ** [comment]
`$sn` is not declared in main scope. There is `socialNetwork` declared. `$sn` is declared only in declarations and functions for shorter code

MA

**Pull request merged**
