### PR TITLE
Include http_build_query() for php4

### PR DESCRIPTION
**Pull request by Kamahl19**
phpBB 3.0 requires PHP 4.3.3 and SN too however http_build_query() is only in php5. therefore we need to include it to the code

https://www.phpbb.com/community/viewtopic.php?f=70&t=2008845&p=13200908#p13200647

something like this

``` php
if (!function_exists('http_build_query')) {
function http_build_query($data, $prefix='', $sep='', $key='') {
   $ret = array();
   foreach ((array)$data as $k => $v) {
       if (is_int($k) && $prefix != null) $k = urlencode($prefix . $k);
       if (!empty($key)) $k = $key.'['.urlencode($k).']';

       if (is_array($v) || is_object($v))
           array_push($ret, http_build_query($v, '', $sep, $k));
       else    array_push($ret, $k.'='.urlencode($v));
   }

   if (empty($sep)) $sep = ini_get('arg_separator.output');
   return implode($sep, $ret);
}}
```

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
remove the https://github.com/Kamahl19/phpBB-Social-Network/commit/55896d18f20dc04aa6623df5a7ccc62074545966 and than I could give you MA

**Comment by Culprit-CZ** [comment]
MA

**Comment by senky** [comment]
`http_build_query()` is also used in [/root/socialnet/profile.php](https://github.com/phpBB-Social-Network/phpBB-Social-Network/blob/develop/root/socialnet/profile.php#L58), so it should be included in `snFunctions`.

Also I am not sure function you used supports array parametres, please, verify it.

**Comment by Kamahl19** [comment]
good point

**Comment by senky** [comment]
That is why I posted 2 versions of this function by myself. Second one should be capable of array parametres.

Also, fallback function must accept all parametres just like [original one](http://php.net/manual/en/function.http-build-query.php).

**Pull request closed without merging**
