### PR TITLE
Format date in profile.php Birthday according to user preferences

### PR DESCRIPTION
**Pull request by senky**
Currently, date in Birthday label in Info tab in profile.php uses force-written format. It should be up to user how to display it.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4243

### CODE REVIEW

**Comment by Kamahl19** [comment]
So what is your conclusion?

**Comment by senky** [comment]
We left decision on you.

**Comment by Culprit-CZ** [comment]
We left decision on you.
1. You declare in lang format date for date of birth
2. We use regular expression to cut current part of user setting to display correctly date od birth

**Comment by Kamahl19** [comment]
I am for 2nd solution

**Comment by senky** [comment]
After long discussion we decided to use solution as proposed in the commit of this PR.

**Comment by Culprit-CZ** [comment]
MA

**Pull request merged**
