### PR TITLE
Add autofocus on username in issue2pr.php

### PR DESCRIPTION
**Pull request by senky**
Just to save time.

### CODE REVIEW

**Comment by Kamahl19** [comment]
MA

**Comment by Culprit-CZ** [comment]
I think it is necessary to give this page some design such as http://manage.phpbb3hacks.com/git-tools/#
Otherwise MA

**Comment by senky** [comment]
Why do you need design for everything? It is simple, 4-input, internally used-only form. I can see no advantage in adding an design, in opposite to longer load and reindering of the page.

**Comment by Culprit-CZ** [comment]
I like simple design. I hate/don't like designed pages.

**Comment by senky** [comment]
So why do you you want to give a design to that page. The simpler it is, the better for us. It is not used by public, so we do not need to style it, IMHO.

**Comment by senky** [comment]
After private discussion, Culprit is giving MA to this.

**Pull request merged**
