### PR TITLE
Change "You have no notification "

### PR DESCRIPTION
**Pull request by Culprit-CZ**
change

You have no notification
to
You have no new notifications

http://phpbbsocialnetwork.com/viewtopic.php?f=6&t=4719

### CODE REVIEW

**Comment by woipi90** [comment]
wouldnt it be you have no new notifications?

**Comment by senky** [comment]
Yes, @Culprit-CZ, you missed the "s" at the end of "notification". It should look like this:
You have no new notifications

**Comment by senky** [comment]
MA

Do not forget to squash the commits first.

**Comment by Kamahl19** [comment]
MA

**Pull request merged**
