### PR TITLE
Blocked and deactivated users are shown in friends sections

### PR DESCRIPTION
**Pull request by senky**
If you block or deactivate user via ACP, it is still displayed in friends section all over the SN. SN friends listing function should contain automatic filter to remove blocked and deactivated users from list, so that we does not need to specify it manually in all friends listings.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4474

### CODE REVIEW

**Comment by senky** [comment]
@Kamahl19: filter should be included in sql query. This means, it will filter out only users that are currently disabled or banned.

**Comment by Kamahl19** [comment]
I dont know .. In my opinion we should not hide banned and deactivated users. I have no problem with them in friend lists. If user dont want them to appear in his friend list he can simply delete them. Otherwise he will wonder why some of his friends are not in his friendlist

**Comment by senky** [comment]
The problem is, that you cannot communicate with that users in no way when they are deactivated/banned. You cannot chat with them, post statuses on their walls, nothing. They, in fact, do not exist. This is how it works in whole phpBB (just check memberlist).
But the thuth is, that banned users are displayed. However, it is another point of view to look at banned users in forums and in social network. I think banned users should be removed as well. I have attached commit that filters both. I can remove banned users filter, but I am against it. @Culprit-CZ, please, express yourself!

**Comment by Culprit-CZ** [comment]
Totaly right, BANNED and IGNORED users should not be included.
MA

**Comment by Kamahl19** [comment]
MA

**Pull request merged**
