### PR TITLE
Prepare repo to be released as 0.7.2

### PR DESCRIPTION
**Pull request by senky**
Change version in install_mod.xml.
Add update_from_0.7.1_to_0.7.2.xml.
update database:
install_sn.php
update_database_dev.php

+
prepare master branch

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
WRONG ;(

**Comment by Kamahl19** [comment]
whats wrong

**Comment by Culprit-CZ** [comment]
MA

**Comment by Kamahl19** [comment]
MA

**Pull request merged**
