### PR TITLE
Comment boxes of more loaded statuses does not resize on focus

### PR DESCRIPTION
**Pull request by Culprit-CZ**
If you click on comment box, it doubles its height. However, when you load more posts, comment boxes of those loaded statuses does not double its height on focus.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4415

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
It is now independent from #116

**Comment by Kamahl19** [comment]
MA

**Comment by senky** [comment]
I just realised that it was using string instead of boolean because it used data-elastic properity, which is used by .elastic plugin, too. So it can be reverted back to 31b6055 and use string comparison in condition if you like (and it seems to be better solution, too, because it is compatibile with .elastic plugin).

**Comment by Culprit-CZ** [comment]
Done

**Comment by senky** [comment]
MA

Please, reword commit so that it is more descriptive (just copy title of this PR) and you can merge it.

**Pull request merged**
