### PR TITLE
Make README more catchy and full of information (master branch)

### PR DESCRIPTION
**Pull request by senky**
Looking at [Top ten reasons why I won’t use your open source project](http://thechangelog.com/post/3032074343/top-ten-reasons-why-i-wont-use-your-open-source-project), it looks like our README is just peace of ... well, you know :). So README should include:
- Description
- Installation instructions
- Where to get help
- Contribution guidelines
- Contributor list
- Credits, Inspiration, Alternatives

### CODE REVIEW

**Comment by Kamahl19** [comment]
Millstone 0.7.3? :) Why

**Comment by senky** [comment]
Sorry, it was removed.

**Comment by Culprit-CZ** [comment]
MA

**Comment by Kamahl19** [comment]
MA

**Comment by ernestbuffington** [comment]
Do you plan on finishing this masterpiece? I'm not sure what happened or why nobody is working on this but I sure hope you come to your senses and come back. It is bad luck to abandon a project of this depth. I would be glad to help out if you need some help. ernest.buffington@gmail.com or 813-846-2865

**Pull request merged**
