### PR TITLE
Confirm box shadow does not move if draggable enabled

### PR DESCRIPTION
**Pull request by Culprit-CZ**
http://phpbbsocialnetwork.com/viewtopic.php?f=62&t=4184

### CODE REVIEW

**Comment by senky** [comment]
What lines was changed really? This PR tries to change a really big block of code, what, at least for me, is unacceptable.

**Comment by Culprit-CZ** [comment]
`m.confirmBox.js` is correctly displayed. There was some smaller changes by declaration.
`m.socialnet.js` was mostly changed at this part

```
confirmBox: {
}
```

Than I move function `dropShadow` to `confirmBox:{}`

That is the main reason why the file is mostly marked as changed

**Comment by senky** [comment]
Alright, if 668dbcd belongs to this PR too: MA

**Comment by Culprit-CZ** [comment]
Should belongs to this PR

**Pull request merged**
