### PR TITLE
Make HTML code more clear

### PR DESCRIPTION
**Pull request by senky**
1. root/styles/prosilver/template/socialnet/user_profile_body.html line 55 - `style="cursor:default;"` should be replaced by class.
2. root/styles/prosilver/template/socialnet/ucp_profile.html - all `<textarea>` elements must have `cols` attribute specified.

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4542

### CODE REVIEW

**Comment by senky** [comment]
To follow W3C, XHTML validation rules, remove browser errors, etc.

**Comment by Kamahl19** [comment]
MA

**Comment by Culprit-CZ** [comment]
MA

**Pull request merged**
