### PR TITLE
Update jquery.jgrowl

### PR DESCRIPTION
**Pull request by Kamahl19**
update jquery.jgrowl to 1.2.5

### CODE REVIEW

**Comment by senky** [comment]
`jquery.jgrowl_minimized.js` should be called `jquery.jgrowl.min.js` (regardless of what name author provides, we should keep consistency which is using `.min.js` appendix for minified files).

**Comment by Culprit-CZ** [comment]
MA

**Comment by senky** [comment]
MA

Squash the commits before you merge PR, please.

**Comment by senky** [comment]
Kamahl, please squash the commits and merge this PR. It is crucial to test and merge #185.

**Comment by Culprit-CZ** [comment]
I think that this is updated with #218 
CSS is updated trough #185 

I think that due to the inactivity of the author it is possible to close this issue

**Comment by senky** [comment]
True, I am closing this PR.

**Pull request closed without merging**
