### PR TITLE
Undefined index: TRANSLATION_INFO in hook_sn-theme.php

### PR DESCRIPTION
**Pull request by Culprit-CZ**
`[phpBB Debug] PHP Notice: in file [ROOT]/includes/hooks/hook_sn-theme.php on line 164: Undefined index: TRANSLATION_INFO` error appears when lessphp compiling results in error and default language is set to English (because it does not have `'TRANSLATION_INFO'` language key.

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
#### Requires

[Issue #106](https://github.com/phpBB-Social-Network/phpBB-Social-Network/pull/106)

**Comment by Kamahl19** [comment]
MA

**Comment by senky** [comment]
As this PR requires #106, you should remove f46ee1c from this one. dcd1b0c should be removed at all, 72645fe lacks message. Otherwise looks good.

**Comment by Culprit-CZ** [comment]
I try to remove your suggestion. And it closed and I could not reopen.
The code has been deleted ;-(

**Pull request merged**
