### PR TITLE
Unify deleting statuses and comments

### PR DESCRIPTION
**Pull request by senky**
When status is collapsed and you click Delete, it displays short status in confirm box.
When status is expanded, it displays the whole status in CB.

However, when comment is collapsed, it displays the whole comment in CB. I think this should be unified and only display collapsed comment. 

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4680

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
I think it is OK.
MA

**Comment by Kamahl19** [comment]
MA

**Comment by woipi90** [comment]
i just tried it on my profile on dev board and there it is still the same..
for statuses and comments..

**Comment by senky** [comment]
I am not sure you understand, what does this script do. It should be the same. And...did you clear your browser cache?

**Comment by woipi90** [comment]
i tested it on dev page and no in both cases it is handled different!

**Comment by senky** [comment]
How different? please, post a screenshots, or describe it better, please.

**Comment by woipi90** [comment]
first
second

**Comment by senky** [comment]
What is wrong with this? I cannot see any problem...

**Comment by woipi90** [comment]
is it supposed to act different when collapsed?
the two pictures show the difference on deleting.. its the same status i wanted to delete..
as u can see there isnt even shown the whole statustext when its collapsed..

**Comment by senky** [comment]
Yes. If it is collapesed, only smaller part of a text should be displayed. If it is not collapsed, it should display full text in the prompt as well.

**Comment by woipi90** [comment]
ok.. then it would be good to at least resize the expanded confirmbox..

**Pull request merged**
