### PR TITLE
Tabify HTML

### PR DESCRIPTION
**Pull request by senky**
Template files are quite messy. It should be tabified properly so that it is easier to maintain.

http://phpbbsocialnetwork.com/viewtopic.php?f=6&t=4584

### CODE REVIEW

**Comment by Kamahl19** [comment]
Have you used the Format function from some IDE or have you done it manually? Eclipse has great Format function

**Comment by Kamahl19** [comment]
And I think we could include this to 0.7.3

**Comment by Kamahl19** [comment]
MA

**Comment by Culprit-CZ** [comment]
MA for 0.7.3

**Comment by senky** [comment]
I did it myself so that it keeps logic. Anyway, I would not merge it untill it is properly tested. We should create test package and provide it to our testers, because there may be problems with whitespaces.

**Pull request merged**
