### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by woipi90**

### CODE REVIEW

**Comment by Kamahl19** [comment]
what is this?

**Comment by woipi90** [comment]
sry i think i actually messed up again.. only wanted to add my commit to pr 207 and somehow it split..

**Comment by senky** [comment]
You cannot add commits to any PR. So either comment on the PR and an author will fix it, or send a new PR, which needs to be properly named, described, labeled, milestoned and each commit in it needs to start with `[i/<PR ID>]`.

**Comment by woipi90** [comment]
ok will only comment in future.. ;) sry about this..

so what should i do about this?

Culprit-CZ did include most of my changes anyway in his latest changes in overall_header_hook_js..

**Comment by senky** [comment]
I will close this. Really thanks for your interest. I am looking forward your comments on opened PRs.

**Pull request closed without merging**
