### PR TITLE
Weird search result for guests

### PR DESCRIPTION
**Pull request by senky**
When you are not logged in, you visit activitypage.php and type anything in the searchbox and submit it, it will redirect you to `socialnet/activitypage.php?mode=search` and content of this page is:

> {"user_id":"ANONYMOUS","more":false,"onlineCount":0}

http://phpbbsocialnetwork.com/viewtopic.php?f=44&t=4649

### CODE REVIEW

**Comment by woipi90** [comment]
and plz also include a fix for searching a name which includes "..

**Comment by senky** [comment]
@weirdo90: what fix? Please, post it to the Bug tracker, so that we can review it properly.

**Comment by Culprit-CZ** [comment]
MA

**Comment by Kamahl19** [comment]
MA

**Pull request merged**
