### PR TITLE
Remove phpBB hook after hook function is called

### PR DESCRIPTION
**Pull request by Culprit-CZ**
#### Error

```
Fatal error: Allowed memory size of 44040192
bytes exhausted (tried to allocate 16384 bytes) in
/root/includes/template.php on line 242
```
#### Causes

phpBB hook is called recursively

### CODE REVIEW

**Comment by Culprit-CZ** [comment]
**Kamahl save file in Windows EOL** - we need Unix EOL (smaller file size)

``` diff
45a46,47
>       $phpbb_hook->remove_hook('phpbb_user_session_handler', array('hookSocialNet', 'start_socialNet'));
>       
112c114
<       $phpbb_hook->remove_hook('phpbb_user_session_handler', array('hookSocialNet', 'start_socialNet'));
---
>       
118a121,122
>       $phpbb_hook->remove_hook(array('template', 'display'), array('hookSocialNet', 'template_display'));
>       
```

**Comment by senky** [comment]
MA

**Comment by Kamahl19** [comment]
MA

**Comment by Culprit-CZ** [comment]
NEED to REOPEN

**Pull request merged**
