### PR TITLE
Time for all activities

### PR DESCRIPTION
**Pull request by Kamahl19**
We should unify activities and statuses and add time to activities too

### CODE REVIEW

**Comment by Kamahl19** [comment]
It happend again. How can I delete this commit from my PRs ?

**Comment by Kamahl19** [comment]
Problem is with the "solving the problem with git" commit. How can I remove it ?

**Comment by Culprit-CZ** [comment]
MA

**Comment by senky** [comment]
MA.

And please just wait with merging this PR untill we will release 0.7.1 (and 0.7.2 if needed). If we merge it now, it will be included in 0.7.1, too, what is undesired.

**Pull request merged**
